### ISSUE TITLE
Understanding the choice of Cypress for e2e testing

### ISSUE THREAD

**Issue by jnarowski** [chrisvfritz/vue-enterprise-boilerplate#10]
I've used nightwatch in my past e2e testing fairly successfully. Cypress seems like a very user friendly and pretty alternative, but it also will add a cost to the testing stack - looks like $99 once they launch pricing. 

I just wanted to understand the choice of Cypress for e2e testing and how to best leverage it.

**Comment by chrisvfritz** [comment]
I'll add more notes about this in the doc, but the short answer is they provide a development environment to help you:

- Travel through time to dissect the source of a problem when a test fails
- Discover how to write selectors/tests for various parts of your app, by inspecting that part of the page.
- Easily test in a wide range of screen sizes
- Automatically record video and screenshots for of your tests

And all of that will remain free, as it's all done through their MIT-licensed client. The part they'll eventually be charging for is their dashboard service, which offers even more benefits. 😻

**Comment by jnarowski** [comment]
Love it. It's a great service. Nightwatch can be limited. I've found it difficult to debug. Will be diving into Cypress soon.
