### ISSUE TITLE
"yarn"

### ISSUE THREAD

**Issue by kaigouthro** [chrisvfritz/vue-enterprise-boilerplate#105]
"00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one."

yes, yarn is installed, works for everything else.
cloned repository to new folder, went into new folder, typed yarn... result: is above.

**Comment by chrisvfritz** [comment]
[Is this](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365) possibly the issue you're seeing?

**Comment by kaigouthro** [comment]
i believe it may be. when i kept uninstalling and re-installing yarn
through npm, and apt-get trying to get it to work, i did see a thing
that mentioned cmdtest when i was trying to uninstall yarn with
apt-get in ubuntu 1804

**Comment by kaigouthro** [comment]
thanks!

**Comment by chrisvfritz** [comment]
Welcome. 🙂
