### ISSUE TITLE
Missing username/password in doc

### ISSUE THREAD

**Issue by JavaPantry** [chrisvfritz/vue-enterprise-boilerplate#106]
I could not find any trace of username/password in doc or source. How I could login?

**Comment by Mike-Loffland** [comment]
https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/router/views/login.vue

**Comment by JavaPantry** [comment]
I would like to know what to enter in username field and password field.

**Comment by Mike-Loffland** [comment]
The actual backend login process needs to be implemented by the developer. Chris stubs out an example login action using Axios in the Vuex “auth” module. But, it is only there to exemplify the pattern. 

https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/state/modules/auth.js

**Comment by JavaPantry** [comment]
Got it! Thank you.

**Comment by chrisvfritz** [comment]
I just added some notes about this to the test doc, as well as a placeholder for those inputs in development to help people out. 🙂
