### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by william-pan** [chrisvfritz/vue-enterprise-boilerplate#107]
Case 1:
Login -> (Home) -> Logout

![hometologout](https://user-images.githubusercontent.com/20611735/48298664-e8e44b80-e4fb-11e8-8ed0-7e239e3bec0f.PNG)

Case 2:
Login -> Profile -> Logout

![profiletologout](https://user-images.githubusercontent.com/20611735/48298666-f13c8680-e4fb-11e8-9388-7277ca4ae831.PNG)

**Comment by leosdutra** [comment]
After some digging, I found the issue is here:
![image](https://user-images.githubusercontent.com/17144/48301251-e66cfc00-e4d1-11e8-9ad3-1aaf073860b5.png)

It also happens if you manually try to hit /login route after logged in.

**Comment by chrisvfritz** [comment]
Thanks! I just added some more tests and fixed these. 🙂
