### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Prompt "checkbox" is not registered

### ISSUE THREAD

**Issue by frozonfreak** [chrisvfritz/vue-enterprise-boilerplate#122]
While trying to create new component with hygen  `npm run new component`. 
Following error is displayed

`AssertionError [ERR_ASSERTION]: Prompt "checkbox" is not registered`

**Comment by chrisvfritz** [comment]
Thanks for reporting! Just fixed. 🙂 It was an insufficiently documented breaking change in Hygen.
