### ISSUE TITLE
Asset routes are not relative in Production build

### ISSUE THREAD

**Issue by frozonfreak** [chrisvfritz/vue-enterprise-boilerplate#126]
In production build all asset routes are hardcoded for root path.  So if I host my website in http://example.com/vue-enterprise/  the build will not work.  This will be useful during prototyping and testing phase 

Manually changing path in index.html in dist fixes most error, still a css and javascript path are incorrect.

**Comment by chrisvfritz** [comment]
It sounds like you probably need to configure [the `baseUrl` option for Vue CLI](https://cli.vuejs.org/config/#baseurl). Let me know if that helps. 🙂

**Comment by frozonfreak** [comment]
Yep Missed tat. Thanks

**Comment by chrisvfritz** [comment]
@frozonfreak Just wanted to leave a note that in Vue CLI 3.3, `baseUrl` was deprecated and the [new `publicPath` option](https://cli.vuejs.org/config/#publicpath) should be used in its place. 🙂

**Comment by PhyberApex** [comment]
Just as a little heads up you also need to set the base in the router to that path or else the routing wont work. Took me some time to figure that one out.
