### ISSUE TITLE
wrong object key used

### ISSUE THREAD

**Issue by eli007s** [chrisvfritz/vue-enterprise-boilerplate#130]
in state/modules/users.js 

there is this:
    // 2. Check if we've already fetched and cached the user.
    const matchedUser = state.cached.find((user) => user.name === username)

shouldn't it be this?:
    // 2. Check if we've already fetched and cached the user.
    const matchedUser = state.cached.find((user) => user.username === username)

check against the `user.username` instead of `user.name` when comparing to `username`?

**Comment by chrisvfritz** [comment]
Nice catch! Just fixed. 🙂

**Comment by hanzlahabib** [comment]
Hey @chrisvfritz  i just watched your talk, i wanted to ask general question
as you are caching user is this safe way to manage users for big sites, for example we are running school management project, 
many students register/login 

is there any security issue if we cache individual users?

thanks if you could answer this
