### ISSUE TITLE
Vetur completion: tag casing and child component attributes

### ISSUE THREAD

**Issue by rickyruiz** [chrisvfritz/vue-enterprise-boilerplate#135]
Vetur 0.16.1 introduced a setting called `vetur.completion.tagCasing` :

```
        "vetur.completion.tagCasing": {
          "type": "string",
          "default": "kebab",
          "enum": [
            "initial",
            "kebab"
          ],
          "enumDescriptions": [
            "use the key in `components: {...}` as is for tag completion and do not force any casing",
            "kebab-case completion for <my-tag>"
          ],
          "description": "Casing conversion for tag completion"
        },
```
Since this boilerplate recommends using PascalCase for component names, `settings.json` in `.vscode` most probably should include `"vetur.completion.tagCasing": "initial"`. This will make tag completion and child component attribute completion work.

Tag completion in PascalCase:

![image](https://user-images.githubusercontent.com/12017329/53195352-b81fb200-35d2-11e9-8cf7-e5e0f9f45c5c.png)

Child component attribute completion:

![image](https://user-images.githubusercontent.com/12017329/53195387-d2599000-35d2-11e9-937a-4b431b0f2048.png)

**Comment by chrisvfritz** [comment]
Hm, the autocompletion still doesn't seem to be working with that change. 😕

**Comment by rickyruiz** [comment]
I could not make it work yesterday, but I found the issue in less than 1 min today, literally 😢. I thought the problem was with some settings that you have in the workspace, which is not the case.

The problem is that in `JS` we do not need to use the `.vue` extension when importing a Vue file. We opt-out of type-checking and the `any` type is used.

![image](https://user-images.githubusercontent.com/12017329/53825106-c5259500-3f32-11e9-904a-6218d1a59634.png)

If we add the `.vue` extension that changes:

![image](https://user-images.githubusercontent.com/12017329/53825233-0f0e7b00-3f33-11e9-8a02-d7ad860c50c7.png)

And now it works as expected:

![image](https://user-images.githubusercontent.com/12017329/53825268-2188b480-3f33-11e9-8932-23ab81b079b7.png)

___

This will not work with components registered globally though. This means all the `_base` components completion will not work because Vetur uses the `keys` in the `components` property.

I'll submit an issue to Vetur about the `.vue` extension problem and maybe one about the components registered globally. I'll keep you posted.

**Comment by rickyruiz** [comment]
Apparently you need to add the `.vue` extension for completion to work.

The last sentence of this comment https://github.com/vuejs/vetur/issues/1107#issuecomment-46579116 references this link https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cannot-recognize-my-vue-component-import-such-as-import-comp-from-comp

**Comment by chrisvfritz** [comment]
Thanks for this research. 🙂

**Comment by chrisvfritz** [comment]
I decided to start forcing `.vue` extensions, so this is resolved now.
