### ISSUE TITLE
.gitattributes corrupt png and videos files after push

### ISSUE THREAD

**Issue by Xationch** [chrisvfritz/vue-enterprise-boilerplate#136]
Hello,

Do you know why the .gitattributes file make all the png and videos files not "readable" / "corrupt" after pushing to my bitbucket ?

Thx

**Comment by chrisvfritz** [comment]
I have not encountered any issue myself. What part of .gitattattributes seems to be causing the problem for you?

**Comment by Xationch** [comment]
After searching on stackoverflow (https://stackoverflow.com/questions/19411981/images-corrupt-after-git-push) I found someone who was talking about the same problem.

"Given 8950 4e47 0d0a 1a... vs 8950 4e47 0a1a it's immediately obvious (well... :-) ) that something thought this was a text file and turned CR-LF (0d0a) into LF-only (0a). Are you (or they) using the core.eol attribute and/or other git attributes to manage end-of-line normalization?"

I just deleted the file and it worked again. I'm not a pro but it's seem to be eol=lf

**Comment by Xationch** [comment]
After some new fresh install I got the same problem.

**Comment by chrisvfritz** [comment]
@Xationch Does [this change](https://github.com/chrisvfritz/vue-enterprise-boilerplate/commit/3e468548b13cd5a9a92de61983ade7382ccf964f) help?

**Comment by Xationch** [comment]
@chrisvfritz Yes it's all good. Images and videos are no longer corrupted now.
