### ISSUE TITLE
Markdown multiple line front matter linting issue

### ISSUE THREAD

**Issue by sanscheese** [chrisvfritz/vue-enterprise-boilerplate#138]
Testing this setup with some markdown handled by NetlifyCMS.

Multiple line front matter follows the format for `myContent` below

```
---
title:
myContent: >-
   # This is some text
   So much text goes in here

anotherItem: something-else
---
```
If I run `yarn lint` it keeps adding an additional space before `anotherItem`

**Comment by chrisvfritz** [comment]
Sounds like a bug in either Markdownlint or Prettier. If you identify which, I recommend filing a bug in one of those repos. For what it's worth, it looks like `|-` works fine, which is probably what you really want in your case.

**Comment by sanscheese** [comment]
Cheers, gotten bit closer and reported: https://github.com/prettier/prettier/issues/6031
