### ISSUE TITLE
Is `@vue/eslint-config-prettier` required ?

### ISSUE THREAD

**Issue by peterhpchen** [chrisvfritz/vue-enterprise-boilerplate#148]
There are two points that makes me confused:

1. [`@vue/eslint-config-prettier`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/eslint-config-prettier) is installed in devDependencies , but the boilerplate didn’t use the config of the `@vue/eslint-config-prettier` in the `.eslintrc.js`:

```js
module.exports = {
  ...
  extends: [
    ...
    // @vue/eslint-config-prettier setting
    // '@vue/prettier',

    // eslint-config-prettier setting
    'prettier',
    'prettier/standard',
    'prettier/vue',
    ...
  ],
  ...
}
```

The boilerplate use [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) config instead of `@vue/eslint-config-prettier` config.

2. There are `eslint-config-prettier`, [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) and `prettier` installed in `@vue/eslint-config-prettier`, but it only use `eslint-config-prettier` and `prettier`.

Base on the above I think it should install `eslint-config-prettier`  but uninstall `@vue/eslint-config-prettier`.

If there are any misunderstandings, please feel free to comment below.

Thank you.

**Comment by chrisvfritz** [comment]
I just removed `prettier` from `package.json` (it was there from when I previously had to specify a specific version of `prettier` to make use of a bugfix only available in a PR), so `@vue/eslint-config-prettier` is doing a little more now. Thanks for your attention to detail. 🙂
