### ISSUE TITLE
Router error on logout

### ISSUE THREAD

**Issue by crcatala** [chrisvfritz/vue-enterprise-boilerplate#15]
Seeing the following error when immediately logging out after login:

<img width="578" alt="router-error-on-logout" src="https://user-images.githubusercontent.com/1514479/37191312-60e772a0-2324-11e8-9bb4-100c5f6aad6e.png">

## Steps to reproduce

- [ ] Start the dev server
- [ ] Login to the starter app with `admin`/`password`
- [ ] Immediately click the logout button
- [ ] Observe the error

Interestingly, when navigating to another route before then, the error is not observed

**Comment by chrisvfritz** [comment]
Thanks! I just fixed this. Vue Router needed to be passed writable route config, so I just did a shallow clone of `routeFrom`.
