### ISSUE TITLE
Vuex helpers performance

### ISSUE THREAD

**Issue by Thomerdos** [chrisvfritz/vue-enterprise-boilerplate#150]
Hello, 

Juste a simple question about the state helper file helper.js. Let's say for example that I import a helper that includes about ten actions when I only use one, can this have an impact in terms of performance on the scale of several tens or even hundreds of components? In other words, is it better to import only the datas actually used in the component or does it have little impact?

Thanks in advance.

**Comment by chrisvfritz** [comment]
Great question! There's extremely little impact to performance. 🙂
