### ISSUE TITLE
markdownlintrc cannot be parsed because of comments

### ISSUE THREAD

**Issue by freakezoid** [chrisvfritz/vue-enterprise-boilerplate#151]
Hi,

i tried adding rules to the .markdownlintrc file and was wondering why these rules where are not applied.

If you run `yarn run lint:all:markdownlint -c .markdownlintrc` you can see a message:

> Cannot read or parse config file .markdownlintrc

After removing all comments from the .markdownlintrc the message disappeared and the rules where correctly applied.

I am working on macOS.

**Comment by chrisvfritz** [comment]
The error seems to be the result of a restriction in `markdownlint-cli`, where they require pure JSON rather than JSONC (JSON with comments) when using the `--config`/`-c` flag. I've just fixed this by converting the config to YAML instead, which always allows comments. 🙂
