### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by matheuseabra** [chrisvfritz/vue-enterprise-boilerplate#155]
Hi all,

I believe it would add great value to the project if Docker was supported on `vue-enterprise-boilerplate`. This issue intends to raise an open discussion on adding general Docker technology to enterprise-level projects such as this one.

**How:** 
1. We could start by building a Docker image to the application itself with a simple `Dockerfile`. 
2. Then, we could **decouple E2E testing execution** by building an isolated image for it, and managing services by configuring a `docker-compose.yml` file (that of course would be in later iterations...). 

Benefits of the proposed feature to the project:
1. Homogeneous environment during deployment
2. Flexibility on configuration for different environments
3. Ephemeral nature of containers makes it easy to restart/remove in case something goes wrong
4. Brainstorm more ideas... [WIP]

Please comment any restrictions that needs to be taken into account when implementing this feature.

If the discussion goes well and it's welcomed by maintainers and the community I'd be happy to send a PR for revision. :ship: :package: :man_technologist: 

Feedback appreciated

**Comment by chrisvfritz** [comment]
I think out-of-the-box support for Docker would be nice, but for people who don't want to use Docker, I'd prefer that they never have to think about it. Does that make sense?

**Comment by matheuseabra** [comment]
@chrisvfritz Yes it does, so I guess the best way to approach this would be to support Docker as a completely opt-in feature

**Comment by sobolevn** [comment]
@chrisvfritz maybe it is a good idea to provide links to other templates that have features this template does not have? For example https://github.com/wemake-services/wemake-vue-template has `docker` and `nuxt` support.

I guess it might be a good fit to your 
> Can you build a Nuxt version of this boilerplate?

section.

**Comment by chrisvfritz** [comment]
Just added docker support, along with links to other boilerplate projects in the ecosystem in the README. 🙂

**Comment by sobolevn** [comment]
@chrisvfritz thanks a lot 👍
