### ISSUE TITLE
Adding Storybook vue tests fails to load styles

### ISSUE THREAD

**Issue by freddiv** [chrisvfritz/vue-enterprise-boilerplate#158]
I am trying to add storybook testing to the vue-enterprise-boilerplate. I already went through the learnstorybook tutorial for vue and it went smoothly. When I completed the setup in the vue-enterprise-boilerplate application and completed the tutorial code within this project everything worked except it doesn't pick up the styles. I tried everything I could think of but it just doesn't seem to pick up the styling at all in the storybook served test. Any ideas on what I can try next?

**Comment by mstaniuk** [comment]
@freddiv Could you prepare simple repo with the issue you've encountered?

**Comment by freddiv** [comment]
I have already resolved it except that the fontawesome icons are missing. I
am guessing that is a webpack build issue I will need to figure out. thanks
for getting back to me.

**Comment by chrisvfritz** [comment]
Closing since this is resolved now and Storybook isn't supported in the project (yet) anyway. 🙂
