### ISSUE TITLE
When I use lazyLoadView, and file was not reloaded after the network was restored.

### ISSUE THREAD

**Issue by mangoooooo** [chrisvfritz/vue-enterprise-boilerplate#160]
lazyLoadView:

When I disconnected the network, the file failed to load, and the file was not reloaded after the network was restored.

![lazyLoadView](https://ws1.sinaimg.cn/large/005wMh0nly1g4nwyp25n5g31ha0rc7dj.gif)

When I use the following method：

`component: () => import(/* webpackChunkName: "login" */ '@views/login'),`

File is reloaded.

![normal](https://ws1.sinaimg.cn/large/005wMh0nly1g4nwyshmkxg31ha0rcdod.gif)

**Comment by chrisvfritz** [comment]
Thanks for reporting this! I just fixed it. 🙂
