### ISSUE TITLE
v-bind="$attrs" with Custom Directive

### ISSUE THREAD

**Issue by Xationch** [chrisvfritz/vue-enterprise-boilerplate#161]
Hey,

Actually v-bind="$attrs" and inheritAttrs: false not working with custom directive with custom component that is not a root element. It's normal ? And there is a way to make it work ? Actually i'm making work with a ref. But it's ugly.

// view
```javascript
<BaseFormPassword v-focus.lazy="true"/>
```
// BaseFormPassword.vue
```javascript
// $attrs is empty
<template>
  <div>
    <input
      v-bind="$attrs"
      ...
    />
    ...
  </div>
</template>
```

**Comment by chrisvfritz** [comment]
This is difficult, since directives as they're currently implemented in Vue 2 aren't translated into attributes. Your solution using a ref is unfortunately the best solution I know of for now.
