### ISSUE TITLE
Can't not get popup info

### ISSUE THREAD

**Issue by laypassmail** [chrisvfritz/vue-enterprise-boilerplate#164]
I used `[vue-authenticate](https://github.com/dgrubelic/vue-authenticate)` for login in by Facebook
But, when open popup (authentication facebook), I got errors from `vue-authenticate` is "Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame."
How to resolve it, thanks

**Comment by chrisvfritz** [comment]
This is more a vue-authenticate question than related specifically to this boilerplate, but having implemented other OAuth solutions, you probably have to add `localhost:8080` as an approved domain for the app registered with Facebook.
