### ISSUE TITLE
(Discussion) -- Best way to implement new feature with all tests

### ISSUE THREAD

**Issue by devingray** [chrisvfritz/vue-enterprise-boilerplate#165]
Hi, awesome boilerplate, I love it. And am busy using it to build my next application.

I would like to discuss with anybody that is interested the best way to implement the mock API for new features. 

Example: I want to register a user. What are some of the ways that we could use this boilerplate to create a new user in the mock API to create a new user and build unit tests for this. I think more of a general best practice tutorial would be awesome

**Comment by chrisvfritz** [comment]
It's difficult to have a general best practice for features, but I generally recommend running the same tests against the mock API that are used to test the real API, and writing those tests before you start development on the mock API. Does that help?

**Comment by chrisvfritz** [comment]
Closing for now, but open to reopening if further discussion is needed. 🙂
