### ISSUE TITLE
(Question) Vuex modules structure

### ISSUE THREAD

**Issue by zaken** [chrisvfritz/vue-enterprise-boilerplate#166]
How should we adjust `modules/index.js`  if our modules are in the format:

```js 
// modules/[some-module].js
export default {
  state: { ... },
  mutations: { ... }
}
```

**Comment by zaken** [comment]
To answer my own question: 

We add `.default` here -> `const moduleDefinition = requireModule(fileName).default`

**Comment by chrisvfritz** [comment]
I just made an update so that both styles will just work. 🙂
