### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by plehnen** [chrisvfritz/vue-enterprise-boilerplate#167]
Hey there, it seems like the dependencies are quite "outdated". Especially eslint which has a new major version released.
Is this not updated for a particular reason? I saw the line with ` "eslint-plugin-vue": "vuejs/eslint-plugin-vue#edd5f14",`  - so may be you are intentionally on a lower version?
If not, it would be cool to see how your package.json would look like when it is up to date, since I was actually facing some problems while trying to update it myself. :)

**Comment by chrisvfritz** [comment]
Just updated. 🙂 Mostly they hadn't been updated in a while because I was in the middle of a cross-country move and hadn't started a greenfield project in a while. 😅
