### ISSUE TITLE
Bootstrap-vue to support pascal and kebab casing.

### ISSUE THREAD

**Issue by vishnu5795** [chrisvfritz/vue-enterprise-boilerplate#169]
Please suggest a way to include  Bootstrap-vue in the project without conflicts.

**Comment by chrisvfritz** [comment]
Since this project is built on Vue CLI, which uses Webpack, I recommend following the [instructions for module bundlers](https://bootstrap-vue.js.org/docs#using-module-bundlers) in the Bootstrap Vue docs.
