### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by roblugt** [chrisvfritz/vue-enterprise-boilerplate#173]
Hi Chris

I was looking through your code (amazing job!) and came across utils/format-date.js.  I see this is using the date-fns package, but this is not declared as a dependency in package.json.

It is being brought into you node-modules as a dependency of lint-staged.  But I presume that as you are referring to the module directly it should be included in your package.json?

Best regards
Rob Lugt

**Comment by chrisvfritz** [comment]
Nice catch! Fixed now. 🙂
