### ISSUE TITLE
Organize imports

### ISSUE THREAD

**Issue by marceloavf** [chrisvfritz/vue-enterprise-boilerplate#177]
I saw that there is an extension for eslint to automatically organize imports, allowing them to be more readable, It should be nice to have some in this project.

```
// 3rd party packages
import Vue from 'vue'

// Stores
import Store from '@Store'

// reusable components
import Button from '@components/Button'

// utility functions
import { add, subtract } from '@utils/calculate'

// submodules
import Intro from './Intro'
import Selector from './Selector'
```

**Comment by chrisvfritz** [comment]
I'm open to this. 🙂 What extension is this? Can you show me an example of how you use it in your own projects?

**Comment by marceloavf** [comment]
I'm using this one in some projects with the default config documented over here 

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

There are many options to enforce conventions that when my application became big, I noticed a heavy disorder when not using this rule

**Comment by chrisvfritz** [comment]
Just added this. 🙂
