### ISSUE TITLE
Cypress & Raspberry Pi

### ISSUE THREAD

**Issue by jessicakennedy1028** [chrisvfritz/vue-enterprise-boilerplate#181]
Hey Chris,
Big advocate for this boilerplate and been using for awhile on all my projects, although I am now building a conference room door display schedule and I did my normal routine, yarn install and BOOM! Cypress does not have a candidate for Raspberry processors... So I started to strip all of the cypress testing suite out and that turned sour really quick. By chance any thoughts of having a version without, or a way to use without Cypress?

**Comment by chrisvfritz** [comment]
No plans to maintain a version without Cypress unfortunately, but [here's a diff](https://gist.github.com/chrisvfritz/75a426d3e7545110801df2e9c92081e8) of everything that should be necessary to remove any trace of Cypress or e2e tests. 🙂
