### ISSUE TITLE
How to import font file in _fonts.scss

### ISSUE THREAD

**Issue by ViralS-ducha** [chrisvfritz/vue-enterprise-boilerplate#185]
I tried to import font file and other ways like "@assets/font.." "~@assets/font.."
![screenshot](https://user-images.githubusercontent.com/48541187/70107517-499b7480-1679-11ea-98fc-0df0d4c96403.png)

Folder:
![screenshot](https://user-images.githubusercontent.com/48541187/70107738-f70e8800-1679-11ea-875f-4e41031b4ff9.png)

Show error:
![screenshot](https://user-images.githubusercontent.com/48541187/70107761-05f53a80-167a-11ea-82e3-b8b52dbd3541.png)

So how do i can import font file and use in project ?
Many thanks!

**Comment by mvdt** [comment]
From the `_fonts.scss` file, `src: url('/assets/myfont.woff2') format('woff2'),` works for me

**Comment by rudnovd** [comment]
src: url('~@/assets/fonts/...')

**Comment by chrisvfritz** [comment]
Indeed, what @rudnovd said as [documented here](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tech.md#referencing-aliased-asset-urls).
