### ISSUE TITLE
Can you explain this file or

### ISSUE THREAD

**Issue by atilkan** [chrisvfritz/vue-enterprise-boilerplate#186]
https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/2b052bac9de33712e642a6477ca73643b0d25ae1/src/state/modules/index.js#L61

I don't understand what is going on here. I am trying to make something similar but HMR only works once.

**Comment by joshgrib** [comment]
https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/2b052bac9de33712e642a6477ca73643b0d25ae1/src/state/modules/index.js#L10-L20

This looks to me like a function to scan the file system and include any new Vuex modules that have been created or updated, so whenever the hot reloading gets triggered this makes sure it has all modules in the directory (and children), then back around the function call...

https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/2b052bac9de33712e642a6477ca73643b0d25ae1/src/state/modules/index.js#L57-L65

It updates the state with the data before the update.

Hope this helps!

**Comment by chrisvfritz** [comment]
Unfortunately, I can only make time to offer support for the HMR in this project (though I've added thorough comments to try to make the code easier to reuse). For additional help getting HMR working outside of this project, I recommend the Vue [forum](https://forum.vuejs.org/) or [chat](https://chat.vuejs.org/).

**Comment by chrisvfritz** [comment]
Thanks @joshgrib for filling in to provide more info/context though!
