### ISSUE TITLE
how to do ssr with this project 

### ISSUE THREAD

**Issue by liurongwei** [chrisvfritz/vue-enterprise-boilerplate#187]
I have used this template project to develop a business project , spa not match the requirement , seo needed ,how to make it support ssr feather ?

**Comment by danielroe** [comment]
@liurongwei This is a Vue CLI project so you can follow the instructions at https://ssr.vuejs.org/ or use a framework like https://vapperjs.org/.

If you are looking for information on Feathers, particularly, there are many tutorials including [this one for Nuxt](https://blog.feathersjs.com/ssr-vuejs-app-with-feathers-and-nuxt-bb7dfd3e6397) or [this boilerplate](https://github.com/codingfriend1/Feathers-Vue) that should give you a good idea of where to start.

**Comment by chrisvfritz** [comment]
Thanks @danielroe for the great answer!
