### ISSUE TITLE
::v-deep stylelint problem

### ISSUE THREAD

**Issue by plehnen** [chrisvfritz/vue-enterprise-boilerplate#190]
I've just updated my project (based on vue-enterprise-boilerplate) to the latest package.json and noticed that the css selector `/deep/` is not working anymore.

Apparently this is considered deprecated and we have to use `::v-deep` now - which is fine, but stylelint is currently not accepting this out of the box.

Adding the rule:
```
'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep']
      }
    ]
```

to **stylelint.config.js** fixes this.

**Comment by chrisvfritz** [comment]
Thanks for reporting the issue and solution! I'm going to leave the rule out of the stylelint config though, since the boilerplate uses CSS modules where [this strategy](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tech.md#styling-subcomponents) is preferred.

**Comment by MrTomek** [comment]
### :v-deep is deprication 
 - https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md
### update
Adding the rule:
```
'selector-pseudo-element-no-unknown': [
  true,
  {ignorePseudoElements: ['v-deep','deep']}
]
```
