### ISSUE TITLE
Is prettier stylelint hack still necessary?

### ISSUE THREAD

**Issue by thedamon** [chrisvfritz/vue-enterprise-boilerplate#191]
[This issue](https://github.com/shannonmoeller/stylelint-config-prettier/issues/4) referenced in the [stylelint.config.js](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/stylelint.config.js#L38) is closed now. 

Would it be safe to say that the ["HACK" section for prettier (lines 35-47)](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/stylelint.config.js#L38) might be no longer necessary?

**Comment by chrisvfritz** [comment]
Nope, it isn't! Just removed it. 🙂
