### ISSUE TITLE
Autoformat on save broken in vscode

### ISSUE THREAD

**Issue by Perogy** [chrisvfritz/vue-enterprise-boilerplate#195]
Using VSCode 1.42.1 auto-formatting vue files no longer works. An error message displays at the bottom of the screen "Extension 'Vetur' cannot format FILENAME".

formatting regular js files still appears to work fine.

**Comment by chrisvfritz** [comment]
@Perogy Are you able to replicate this with a fresh clone? I'm guessing there may be some updates to `.vscode/extensions.json` and/or `.vscode/settings.json` that you'll have to pull into your local project.

**Comment by Perogy** [comment]
I did try on a fresh clone, and still got the problem (work machine), however I also tried on my home machine and it worked fine. Clearly a problem with my system and/or configuration. Thanks Chris, closing.
