### ISSUE TITLE
Problems with Visual Studio Code Format Plugin

### ISSUE THREAD

**Issue by mgdodge** [chrisvfritz/vue-enterprise-boilerplate#27]
The 'formatOnSave' setting seems to be causing issues if the [Visual Studio Code Format](https://marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format) plugin is installed. The issue is probably with that plugin, judging by the reviews/comments left over there, but if someone is using that plugin, .vue files get corrupted when saving in this project.

Might be good to at least indicate the setting and how to disable it.

**Comment by chrisvfritz** [comment]
Thanks! I just added a new __Troubleshooting__ section of the docs to better document this and other potential issues people might run into.
