### ISSUE TITLE
Getting started part is not working

### ISSUE THREAD

**Issue by altinselimi** [chrisvfritz/vue-enterprise-boilerplate#29]
Hi, 

I'm following the instructions from the Getting Started section of the readme, but it fails at the third step.

After cloning repo, and going inside the directory, running 
`node _start.js` throws error : 
```
module.js:540
    throw err;
    ^

Error: Cannot find module 'date-fns/format' .....
```
Tried installing date-fns globally, still same error. Running 
`npm install` throws error : 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@2.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@2.1.0 postinstall script.

```

How can I fix this ?

System info: MacOS 10.13.3, NPM v5.6.0, Node v8.9.4

**Comment by TomoGlavas** [comment]
Same thing on Ubuntu 16, NPM v5.3.0, node v8.6.0

**Comment by jnarowski** [comment]
Did you do NPM install first?

**Comment by chrisvfritz** [comment]
Running `npm install` or `yarn install` first will indeed fix it, but I just updated the start script to not rely on any installed dependencies, so it should work.

The Cypress error is something separate though, [tracked here](https://github.com/cypress-io/cypress/issues/1512). It should only happen if you're installing Cypress as the root user though, so I recommend installing without `sudo` (which is better anyway, as it's a good idea to avoid running 3rd-party software with root permissions unless absolutely necessary).
