### ISSUE TITLE
Git shallow clone issue

### ISSUE THREAD

**Issue by kayandrae07** [chrisvfritz/vue-enterprise-boilerplate#35]
Hi!

On the readme, the recommended way of installing this project from scratch is to create a shallow clone

```bash
git clone https://github.com/chrisvfritz/vue-enterprise-boilerplate.git my-new-project --depth 1
```

## Problem

This can lead to issues like the **shallow update not allowed** error if you change the remote URL.

## Solution
You will have to re-add this project to your project's remote

```bash
git remote add old https://github.com/chrisvfritz/vue-enterprise-boilerplate.git
``` 

and after that you can

```bash
git fetch --unshallow old
git remote rm old
```

## Outro
I think switching this template to be created by vue cli might work. Just my 2 cents

**Comment by chrisvfritz** [comment]
Thanks for reporting this! I hadn't encountered that error before, but would simply removing `--depth 1` solve the issue?

**Comment by kayandrae07** [comment]
It will be my honour 😄
