### ISSUE TITLE
Sorry for such a NOOB question, but how would i go about orgnaizing the components into folders?

### ISSUE THREAD

**Issue by ctwoodwa** [chrisvfritz/vue-enterprise-boilerplate#37]
I'm planning on having about 400 different pages within my app and I would like to organize the components into folders like components/base/_base++ and components/navbar/navbar vue files.  I was able to move the navbar files to a folder, but i'm having an issue with the base files.  after moving the base files to thier folder the tests no longer pass.

i tried changing the _globals.js to
const requireComponent = require.context(
  // Look for files in the current directory
  './**base**',
  // Look in subdirectories
  false,
  // Only include "_base-" prefixed .vue files
  /_base-[\w-]+\.vue$/
)
![image](https://user-images.githubusercontent.com/1328090/39015857-819f1db6-43ec-11e8-8f32-8d9fff162b5b.png)

**Comment by frandiox** [comment]
@ctwoodwa You can check [this fork](https://github.com/frandiox/vue-enterprise-boilerplate/tree/master/src/components). It places the components inside folders when you create them using `yarn new` 👍

**Comment by chrisvfritz** [comment]
Thanks @frandiox! I also provide a little more detail in [this issue](https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/17#issuecomment-373556252) on why I organize components into a single folder. I'll consider this resolved for now, but happy to reopen if it's not. 🙂
