### ISSUE TITLE
Readme: Clone the repository Error Permission denied

### ISSUE THREAD

**Issue by fmunoz92** [chrisvfritz/vue-enterprise-boilerplate#4]
$ git clone git@github.com:chrisvfritz/vue-enterprise-boilerplate.git
Cloning into 'vue-enterprise-boilerplate'...
Permission denied (publickey).
fatal: Could not read from remote repository.

I suggest 

`git clone https://github.com/chrisvfritz/vue-enterprise-boilerplate.git --depth 1`

**Comment by chrisvfritz** [comment]
Fixed in #5.
