### ISSUE TITLE
Warnings during install and does not work

### ISSUE THREAD

**Issue by julijane** [chrisvfritz/vue-enterprise-boilerplate#40]
Sorry if this is a simple problem, i'm not used to node. I did what the documentation said and this happened:

```
22:44 $ node _start.js 
22:44 $ rm _start.js 

22:45 $ yarn install
yarn install v1.6.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.2" has unmet peer dependency "webpack@>=2".
warning "@vue/cli-plugin-e2e-cypress > eslint-plugin-cypress@2.0.1" has unmet peer dependency "eslint@>= 3.2.1".
warning "@vue/cli-plugin-eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning "@vue/eslint-config-prettier > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning "@vue/eslint-config-standard > eslint-config-standard@11.0.0" has unmet peer dependency "eslint@>=4.18.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.9.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.0.1" has unmet peer dependency "eslint@>=3.19.0".
warning " > @vue/test-utils@1.0.0-beta.12" has unmet peer dependency "vue-server-renderer@2.x".
warning " > sass-loader@6.0.7" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
Done in 208.40s.

22:50 $ yarn dev --open
yarn run v1.6.0
$ vue-cli-service serve --open
 INFO  Starting development server...
 10% building modules 1/1 modules 0 activeevents.js:165                            
      throw er; // Unhandled 'error' event

Error: watch /home/jule/ocs/socketchat/public ENOSPC
    at FSWatcher.start (fs.js:1409:19)
    at Object.fs.watch (fs.js:1435:11)
    at createFsWatchInstance (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:171:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/jule/ocs/socketchat/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/jule/ocs/socketchat/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:171:5)
error Command failed with exit code 1.
```

**Comment by julijane** [comment]
It works when I use `npm install `though.

**Comment by chrisvfritz** [comment]
Thanks for reporting this @julijane. I'm guessing you might be on Linux, where the default max file watchers is usually set to 8192. Installing with Yarn might create more files than installing with NPM, pushing the project over that limit. If you _are_ on Linux, you should be able to increase the limit [with these instructions](
https://stackoverflow.com/questions/22475849/node-js-error-enospc#answer-32600959).

Let me know if that helps! 🙂

**Comment by julijane** [comment]
Thank you, that fixes it indeed. The warnings about unmet dependencies persist, though. While apparently they are harmless, if one does not know they are quite unsettling (but might not be your fault, I don't understand that enough, yet).

**Comment by chrisvfritz** [comment]
I agree the warnings are annoying. 😄 That's a problem on Yarn's end that was fortunately fixed in version 1.4, so if you upgrade Yarn and try installing again, you shouldn't see them anymore. Let me know if that works for you. 🙂

**Comment by julijane** [comment]
well...

```
$ yarn -v
1.6.0
```

**Comment by chrisvfritz** [comment]
Sorry, I was thinking of [this similar issue](https://github.com/yarnpkg/yarn/pull/5088). 😅 You're absolutely right and I [just opened an issue](https://github.com/vuejs/vue-cli/issues/1243) in Vue CLI proposing a potential fix for those warnings.

In case you're curious, Yarn (unlike NPM) doesn't recognize hoisted sub-dependencies as peer dependencies - so even though everything works, it still complains when no matching top-level dependency is found. Since this isn't something I can fix from here though, I'll close the issue.

Thanks for your patience. 🙂

**Comment by julijane** [comment]
Understood. So thanks for your help so far. May I suggest that a hint regarding the file limitation on Linux is added to the documentation? While this is nothing specific of this package, I guess a one-liner should do and won't harm?

**Comment by chrisvfritz** [comment]
Great idea. 🙂 Just added that note.

**Comment by dyardyGIT** [comment]
I just cloned the latest and could not run node _start.js
yarn install -- worked

yarn dev --open -- did not work first time
I then tried npm run dev ---this worked
I went back in retried yarn dev --open and it worked only after npm run dev

odd
