### ISSUE TITLE
@import '~@design' error in src/components/_base-input.vue 

### ISSUE THREAD

**Issue by stuta** [chrisvfritz/vue-enterprise-boilerplate#42]
I did yarn upgrade and I get this error if file src/components/_base-input.vue.

@import '@design'; does no cause an error, @import '~@design'; does.

**Comment by chrisvfritz** [comment]
It sounds like before running `yarn upgrade`, you might have updated package.json to use sass-loader >=7.0.0, which is a major version bump with [this issue](https://github.com/webpack-contrib/sass-loader/issues/566). It seems they accidentally broke backwards-compatibility when refactoring alias support. 😅

I just upgraded the project to sass-loader 7.0.x with the necessary changes.
