### ISSUE TITLE
Vuetify

### ISSUE THREAD

**Issue by Teodorko** [chrisvfritz/vue-enterprise-boilerplate#48]
Hello!
Excuse me for my English)

I added a vuetify to this boilerplate.
But the components do not use colors from the theme.
for example
<v-btn color="primary" />
looks like this
![image](https://user-images.githubusercontent.com/20430124/40513508-a6351292-5fae-11e8-8aee-dd01498c19e5.png)

and vuetify object
![image](https://user-images.githubusercontent.com/20430124/40513530-b9bca910-5fae-11e8-8b02-9b4b8a4f6fcb.png)

I hope you can tell me what I'm doing wrong.

**Comment by dannyrb** [comment]
Are you wrapping everything in `<v-app>`? I think that's what provides the context for which theme variables to use (I could be wrong).

**Comment by Teodorko** [comment]
Yes i do.
All the components work correctly. I can even assign a color.
![image](https://user-images.githubusercontent.com/20430124/40532073-f591efd8-6006-11e8-9712-387aacc68986.png)
`<v-tooltip
      slot="actionButton"
      bottom
    >
      <v-btn
        slot="activator"
        color="light-green"
        dark
      >
        <v-icon>add</v-icon>
      </v-btn>
      <span>Add new document</span>
    </v-tooltip>`
Only theme colors do not work

**Comment by Teodorko** [comment]
@chrisvfritz may be you can help me :)

**Comment by chrisvfritz** [comment]
@Teodorko Unfortunately, I don't have any ideas. 😅 I've never used Vuetify themes and can't think of anything specific to this boilerplate that might cause the problem. If it's possible to provide a link to the source code, it's possible someone else may be able to see what's going wrong.

**Comment by frandiox** [comment]
I just mentioned this in #45. I believe it's the same issue. Use `metaInfo` instead of `page` for providing information to `vue-meta` and it will work :+1:

**Comment by Teodorko** [comment]
@frandiox 
Thank you very much friend !!

1) src/router/index.js
Vue.use(VueMeta, {
  keyName: 'page', --> keyName: 'metaInfo'
})
2) in components
  page -> metaInfo
And it's works!

![image](https://user-images.githubusercontent.com/20430124/40577420-f55795d8-610d-11e8-8f81-ebe772ec5ba1.png)
`      <v-btn
        :loading="tryingToLogIn"
        :disabled="tryingToLogIn"
        color="primary"
        block
        type="submit"
      >
        Login
      </v-btn>`

**Comment by pynner** [comment]
Can confirm this is still an issue, Vuetify colors have no effect until the above change is made

**Comment by dyardyGIT** [comment]
Is there a github sample of using vuetify.  I am oddly still getting lots of odd errors 

i.e.
importing through at runtime (dependency injection), move `index.js` to same directory as `nprogress/nprogress` or consider making `nprogress/nprogress` a package  import/no-relative-parent-imports
  7:1   error  `@state/store` import should occur before import of `vue`
