### ISSUE TITLE
yarn lint breaks _typography.scss

### ISSUE THREAD

**Issue by apokokki** [chrisvfritz/vue-enterprise-boilerplate#51]
"yarn lint" breaks _typography.scss file in windows 10 after clean install (tested with two machines).

yarn lint
yarn run v1.7.0
$ eslint --ext .js,.vue --fix . && stylelint --fix "src/**/*.vue" "src/**/*.scss" && markdownlint docs/*.md *.md && prettier --list-different --write "**/*.{js,json,css,scss,vue,md}"
src\design\_typography.scss
error Command failed with exit code 1.

**Comment by stuta** [comment]
I quess this is crlf vs lf problem.

**Comment by stuta** [comment]
Yarn lint works after changing line endings from crlf to lf.

Maybe adding file .gitattributes ```* text eol=lf``` would be good.
Also changing in all windows gitconfig -files ```autocrlf = input``` helps.

**Comment by chrisvfritz** [comment]
I believe this should only be a problem with versions of Git prior to 2.10, but I just added a `.gitattributes` file to fix it in those older versions. Thanks @apokokki for the report and @stuta for the research. 🙂

**Comment by apokokki** [comment]
Thanks Chris - problem solved.
