### ISSUE TITLE
Integration with json-server

### ISSUE THREAD

**Issue by genu** [chrisvfritz/vue-enterprise-boilerplate#54]
Have you considered integrating https://github.com/typicode/json-server as a mock server rather than the current, more manual approach?

It might add some simplicity and make that logic a little more clear.

**Comment by chrisvfritz** [comment]
I'd really love to use some API mocking framework. Unfortunately, when I tried json-server for this purpose, I found it was better suited to quick demos than mocking real APIs. There seemed to be no simple way of handling authentication, authorization, status codes with custom messages, and many other common features of real APIs. So for essentially every route, I had to rely on custom middleware, kind of defeating the purpose.

If these things have changed however, I'm open to re-evaluating json-server. I'm also open to any other API mocking framework. I'm personally keeping an eye on [mirage-server](https://github.com/cowboyd/mirage-server), but right now, it has essentially no documentation.
