### ISSUE TITLE
auth0.com Integrations

### ISSUE THREAD

**Issue by chriswork** [chrisvfritz/vue-enterprise-boilerplate#55]
How would you incorporate a auth0.com integration?

**Comment by chrisvfritz** [comment]
Great question! It looks like Auth0 now has a [tutorial and sample project](https://auth0.com/docs/quickstart/spa/vuejs) specifically for Vue. 🙂 Their sample project is a single-page application just like this boilerplate, so the process should be very similar. If you're logged in to Auth0, the code examples should even have your application data in them!

**Comment by frandiox** [comment]
I made [this](https://github.com/frandiox/vue-graphql-enterprise-boilerplate/blob/master/src/services/auth.js) for Auth0 + GraphQL but it should be very similar for anything else. Hope it helps!

**Comment by chrisvfritz** [comment]
Thanks @frandiox!
