### ISSUE TITLE
.DS_Store file breaks mock-api

### ISSUE THREAD

**Issue by JamesLarson** [chrisvfritz/vue-enterprise-boilerplate#57]
Im working on a mac, the OS put a .DS_Store file into the tests/mock-api/routes/ directory.

This resulted in breaking the require statement on line 9 of tests/mock-api/index.js because the .DS_Store file does not have module.exports defined inside it.
 
I suggest adding something like this before to fix the problem

```
if(fs.existsSync(`${path.join(__dirname, 'routes')}/.DS_Store`)){
    fs.unlinkSync(`${path.join(__dirname, 'routes')}/.DS_Store`)
  }
```

I have not gone through the rest of the project to see if entire directories of files are being required in this way elsewhere, but a project wide solution to this problem may be better.

**Comment by JamesLarson** [comment]
on second thought, a more elegant solution may be to loop over only files with a .js extension

**Comment by chrisvfritz** [comment]
I just added a fix for this. Thanks for reporting it! 🙂
