### ISSUE TITLE
Question: Components as separate directories 

### ISSUE THREAD

**Issue by mercs600** [chrisvfritz/vue-enterprise-boilerplate#6]
Firstly, very good boilerplate. 
I wonder about components location. From my point of view you should keep components as separate directories. In case when you have multiple files for each components like unit tests etc. and in the future it might be more. So when amount of global components will be bigger, this folder might be a bit messy. What do you think ? It is dictated by _globals.js for global component registering ?

**Comment by chrisvfritz** [comment]
Thanks! I personally don't recommend component folders just for component/test pairings, as I feel it makes the `components` directory more difficult to traverse overall. However, when a team decides they want 3 or more adjacent files for components (e.g. `.vue` file, unit test, separate `.scss` file, and storybook example), that's the tipping point where I think folders might be a good idea.

That's just my opinion though, biased by my own experiences. I think if component folders even with 1 file makes your team happy and productive, then you should use them. 🙂

**Comment by chrisvfritz** [comment]
Closing for now, but happy reopen is there are any follow-up questions/suggestions. 🙂
