### ISSUE TITLE
problem with background url 

### ISSUE THREAD

**Issue by Mobeidat** [chrisvfritz/vue-enterprise-boilerplate#61]
Using the @assets alias on background-image: CSS attribute is not working

it's not reading the root path

ex: background-image: url('@assets/images/1.jpg'); 

the image will not be rendered on the browser

**Comment by chrisvfritz** [comment]
Try:

```css
background-image: url('~@assets/images/1.jpg');
```

(With the tilde.)

I'll add a note about this to the docs.
