### ISSUE TITLE
Mentions of polyfill.io are redundant

### ISSUE THREAD

**Issue by sodatea** [chrisvfritz/vue-enterprise-boilerplate#73]
Now that the project has upgraded to use modern mode, polyfill.io related code has been removed, these paragraphs in the documentation are no longer necessary:

- https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tech.md#polyfills
- https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tech.md#javascript-faq (the second question)

**Comment by frandiox** [comment]
Same as https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/68
