### ISSUE TITLE
Why use so many parameters when creating command 'unit'?

### ISSUE THREAD

**Issue by elevatebart** [chrisvfritz/vue-enterprise-boilerplate#74]
The best way to run jest unit tests is `yarn unit`.
It will run `vue-cli-service test:unit \\.unit\\.js$`.
Why filter again on `\\.unit\\.js$`? The jest.config.js `testMatch` param seems to be the same. 

What am I missing?

If we remove the filter here, it allows users to do the classic 
```
yarn unit button
```
very useful to run a subset of the tests instead of the whole suite.

Thank you for your answers.

**Comment by chrisvfritz** [comment]
I believe this was necessary with a previous version of Vue CLI, but it looks like we've since fixed it, so the `\\.unit\\.js$` is now removed. 🙂
