### ISSUE TITLE
coverage report is getting 404

### ISSUE THREAD

**Issue by genu** [chrisvfritz/vue-enterprise-boilerplate#82]
When I generate a coverage report and navigate through it I get a 404 when I click on a source file.

![image](https://user-images.githubusercontent.com/928780/44914544-936f0f80-acfe-11e8-88ca-75ff8dcd134d.png)

**Comment by chrisvfritz** [comment]
The unit coverage report is not actually part of your app, so shouldn't be accessible for a local server like `localhost:5000`. Instead, it's bundled into `tests/unit/coverage/lcov-report`. To view it, you'll actually want to open `tests/unit/coverage/lcov-report/index.html` with the `file://` protocol, which is usually the default behavior for opening a local HTML file. Then all the links should work. 🙂

Does that make sense?

**Comment by genu** [comment]
What I did, is, I used `server` or `live-server` package to serve the coverage folder.

You're right, the coverage should not be served through a server, but accessed directly.

That was the issue.

We can close this (maybe a note should exist somewhere about this behavior?)
