### ISSUE TITLE
Prettier missing when trying to run _start in fresh clone

### ISSUE THREAD

**Issue by davestaab** [chrisvfritz/vue-enterprise-boilerplate#91]
Hey Chris, 

I made a fresh clone of your project and was following the instructions in the [readme](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/README.md). 

When running step 3 `node _start` fails because `_start`  requires `./aliases.config` which requires `prettier` which isn't available yet. 

I ran `yarn` before step 3 and confirmed `node _start` now works when I run it. (I had to discard changes to the README to rerun it.) So maybe step 2.5 should be added to run `yarn install` first? 

Keep up the good work! 👍

**Comment by chrisvfritz** [comment]
Thanks for reporting that! Just updated. 🙂
