### ISSUE TITLE
Determining initial page load

### ISSUE THREAD

**Issue by alexdilley** [chrisvfritz/vue-enterprise-boilerplate#94]
I see you use the [lack of] presence of a route name ([here](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/921818067c386fd875c16dac38a04739e29c08e9/src/router/index.js#L37)) to determine whether a navigation is the initial page load (where Vue Router appears to have [an unnamed version of] the root path set as the `from` route when the page is first loaded). But what if I define a route in my app that I don't/forget (bad practice, maybe!) to name? I've hunted for another way to determine whether a view is rendered as a result of, say, refreshing the page, but I can't see anything – I guess access to the history stack/length could provide a solution. I see you've opened an [issue](https://github.com/vuejs/vue-router/issues/883) relating to gaining access to the `referer` (tradition denotes you should spell it wrong (:) – does this allude to a potential omission of Vue Router that could be explored, do you think? I suppose it is earmarked for v3 so perhaps this point is moot post the next release...

**Comment by chrisvfritz** [comment]
That's a great point about `route.name`! 🙂 I just updated the router to check for `null` specifically, so now accidentally leaving the name out shouldn't cause an issue.

**Comment by alexdilley** [comment]
> I just updated the router to check for null specifically, so now accidentally leaving the name out shouldn't cause an issue.

👍 nice.

Great to meet you at Vue London, albeit briefly. I hope you had an enjoyable trip over.

**Comment by chrisvfritz** [comment]
Great to meet you as well! 🙂
