### ISSUE TITLE
Live refresh data not working even refreshing browser

### ISSUE THREAD

**Issue by hjJunior** [chrisvfritz/vue-enterprise-boilerplate#95]
For some reason my application doesn't refresh automatically, My application don't even refresh using browser, so unique way to get new editions is stoping the method `dev` and running again
So sorry, I don't know if is a problem when a application is growing with Vue Cli 3, actualy my application I didn't have done much things, I just created just 2 more _base-components and edited the login view, by the way I'll provide a repo

- vue: 3.0.3

**Comment by hjJunior** [comment]
So here u can find the [repo](https://github.com/hjJunior/issue-95-vue-enterprise-boilerplate)
The problem happens when I edit the file `src/router/views/login.vue` I just got to see the changes if I stop the application and run again

**Comment by hjJunior** [comment]
So for example changing 

```diff
-        <BaseCheckbox label="Text here" />
+        <BaseCheckbox label="New Text here" />
```

**Comment by chrisvfritz** [comment]
Thanks for reporting the issue and providing a reproduction. 🙂 Could you also provide the versions for your operating system, Node, and Yarn?

**Comment by hjJunior** [comment]
Of course, I'm realy glad for your project, its amazing ;) 

- node: v10.10.0
- yarn: 1.9.4

Running on Linux (Ubuntu 18)

**Comment by hjJunior** [comment]
did you got to reproduce it?

**Comment by hjJunior** [comment]
@chrisvfritz did you got to reproduce it?

**Comment by chrisvfritz** [comment]
No, I haven't been able to unfortunately. I've tested with these exact versions of Node, NPM, and Yarn (though not on Ubuntu 18 yet), but didn't see the problem. 😕

**Comment by andthomas** [comment]
@hjJunior are you sure you're running the project from the right directory, and that you don't have another version of the project that you're editing?

**Comment by hjJunior** [comment]
I don't  know the why, but upgrading to yarn 1.10.1 its works

**Comment by chrisvfritz** [comment]
Glad it resolved itself! 🙂
