### ISSUE TITLE
Webpack Compression

### ISSUE THREAD

**Issue by n1cator** [chrisvfritz/vue-enterprise-boilerplate#96]
I feel like in a Production Build it would be nice to offer compressed .js files (for Mobile Users) e.g. gzip, compression-webpack-plugin could be a Candidate for this.

**Comment by chrisvfritz** [comment]
I believe most static site hosts (e.g. Netlify, Surge) and web servers (nginx, Express, Hapi, etc) can automatically gzip assets for you, so this is usually more of a backend than frontend concern.

**Comment by n1cator** [comment]
@chrisvfritz Works well with the nginx [gzip_static](https://killtheradio.net/technology/using-gzip_static-in-nginx-to-cache-gzip-files/) module but I would still provide a PR if wanted.

**Comment by chrisvfritz** [comment]
There are a couple reasons compression isn't already built into this project (or Vue CLI). Gzipping here would:

- increase build times (unnecessarily, most of the time)
- imply that the mere existence of gzipped assets is sufficient, when they won't actually do anything unless the server is configured to serve them, and with `Content-Encoding: gzip`

Does that make sense?
